name: Multi-Target Build AmneziaWG

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: "OpenWrt version"
        required: true
      amneziawg_version:
        description: "AmneziaWG version"
        required: true
      compile_kmod:
        description: "Compile kernel module"
        type: boolean
        required: true
        default: true
      compile_go:
        description: "Compile Go implementation"
        type: boolean
        required: true
        default: true

  workflow_call:
    inputs:
      openwrt_version:
        required: true
        type: string
      amneziawg_version:
        required: true
        type: string
      compile_kmod:
        required: true
        type: boolean
      compile_go:
        required: true
        type: boolean


jobs:
  generate-matrix:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Generate build matrix
        id: set-matrix
        run: |
          MATRIX=$(node index.js ${{ inputs.openwrt_version }})
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT


  build-awg:
    needs: generate-matrix
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: amneziawg

      - name: Check if ZIP already exists in release
        id: check_zip
        env:
          VER: ${{ inputs.openwrt_version }}
        run: |
          NAME="OpenWRT-awg-2-${VER}-${{ matrix.target }}-${{ matrix.subtarget }}-${{ matrix.pkgarch }}.zip"

          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${VER})

          if [ "$STATUS" != "200" ]; then
            echo "zip_exists=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          FILE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${VER} \
            | jq -r ".assets[]?.name" | grep -Fx "$NAME" || true)

          if [ "$FILE" != "" ]; then
            echo "zip_exists=true" >> $GITHUB_OUTPUT
          else
            echo "zip_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip target (ZIP already exists)
        if: steps.check_zip.outputs.zip_exists == 'true'
        run: echo "ZIP already exists — skipping build."

      - name: Exit early
        if: steps.check_zip.outputs.zip_exists == 'true'
        run: exit 0


      # ---------- СБОРКА СТАНДАРТНАЯ ----------
      - name: Checkout OpenWRT Packages repository
        uses: actions/checkout@v4
        with:
          path: packages
          repository: openwrt/packages
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pyelftools python3-dev python3-setuptools swig curl zip zstd jq

      - name: Download and prepare SDK
        run: |
          VERSION="${{ inputs.openwrt_version }}"
          TARGET="${{ matrix.target }}"
          SUBTARGET="${{ matrix.subtarget }}"

          if [ "$VERSION" = "SNAPSHOT" ]; then
              MIRRORS=("https://downloads.openwrt.org/snapshots/targets/$TARGET/$SUBTARGET")
          else
              MIRRORS=(
                "https://downloads.openwrt.org/releases/$VERSION/targets/$TARGET/$SUBTARGET"
                "https://mirror-03.infra.openwrt.org/releases/$VERSION/targets/$TARGET/$SUBTARGET"
                "https://mirror-01.infra.openwrt.org/releases/$VERSION/targets/$TARGET/$SUBTARGET"
                "https://mirror-02.infra.openwrt.org/releases/$VERSION/targets/$TARGET/$SUBTARGET"
              )
          fi

          sdk_url=""
          for BASE in "${MIRRORS[@]}"; do
            sdk_url=$(curl -fsSL "$BASE" | grep -oP 'openwrt-sdk[^<"]+(tar\.zst|tar\.xz)' | head -n1)
            if [[ -n "$sdk_url" ]]; then
                break
            fi
          done

          curl -fsLO --location "${BASE}/${sdk_url}"
          tar -xf $(basename "$sdk_url")
          rm -f *.tar.zst *.tar.xz
          mv openwrt-sdk* openwrt

          echo "src-cpy awgopenwrt ../amneziawg" >> openwrt/feeds.conf.default
          ./openwrt/scripts/feeds update -a

          curl -fsL "$BASE/config.buildinfo" > openwrt/.config
          echo "CONFIG_PACKAGE_kmod-amneziawg=y" >> openwrt/.config
          echo "CONFIG_PACKAGE_amneziawg-go=y" >> openwrt/.config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> openwrt/.config
          echo "CONFIG_PACKAGE_luci-proto-amneziawg=y" >> openwrt/.config

          ./openwrt/scripts/feeds install -a
          make -C openwrt defconfig

      - name: Compile AWG packages
        run: |
          cd openwrt
          if [ "${{ inputs.compile_kmod }}" = "true" ]; then
              make package/kmod-amneziawg/{clean,download,prepare,compile} -j$(nproc)
          fi
          if [ "${{ inputs.compile_go }}" = "true" ]; then
              make package/amneziawg-go/{clean,download,prepare,compile} -j$(nproc)
          fi
          make package/amneziawg-tools/{clean,download,prepare,compile} -j$(nproc)
          make package/luci-proto-amneziawg/{clean,download,prepare,compile} -j$(nproc)

      - name: Upload release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VER: ${{ inputs.openwrt_version }}
        run: |
          mkdir -p awgrelease

          cp openwrt/bin/targets/${{ matrix.target }}/${{ matrix.subtarget }}/packages/kmod-amneziawg* awgrelease 2>/dev/null || true

          find "openwrt/bin/packages/${{ matrix.pkgarch }}/" \
            -maxdepth 2 -type f -name '*amneziawg*' -exec cp {} awgrelease \; 2>/dev/null || true

          ZIP="OpenWRT-awg-2-${VER}-${{ matrix.target }}-${{ matrix.subtarget }}-${{ matrix.pkgarch }}.zip"

          zip -r "$ZIP" awgrelease

          gh release create "$VER" --notes "AWG build" --repo "${{ github.repository }}" || true
          gh release upload "$VER" "$ZIP" --clobber --repo "${{ github.repository }}"
